apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: <DOCKER_HUB_USERNAME>/my-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "mysql-service"  # Connect to MySQL using the service name
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password