apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  type: LoadBalancer
  ports:
    - port: 80  # Exposes the app on port 80 (external) and forwards traffic to port 8080 (internal)
      targetPort: 8080
  selector:
    app: my-app